### ISSUE TITLE
Recherche de patients: Liste vide de patients

### ISSUE THREAD

**Issue by vferretti** [Ferlab-Ste-Justine/clin-project#197]
- Allez à la page de recherche de patients
- Chercher matheo belanger avec la boîte de recherche
- Sélectioner le patient  dans la liste des suggestions 
- On se retrouve dans la page patient de Matheo
- Faire back 
- BUG: on se retrouve avec une liste de patients vide

**Comment by nyanofthemoon** [comment]
@vferretti A coupe of things to help me understand what needs to be done for this ticket.

1) "matheo belanger" does not return anything so I cannot reproduce
2) if I do a search on "matheo", I get 1 single result in the autocomplete and if I click on it, I am redirected to the patient details page of "matheo belanger".

I don't think this is a bug because you can search only by "firstname" OR "lastname" and not a combination of several fields in elastic search as this is an "autocomplete":

![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/2c6ee769-afbe-482b-84c6-ed522036a24d)

We could make a new feature request to address searching with the "autocomplete" by concatenating fields together.

**Comment by nyanofthemoon** [comment]
A found a duplicate reference to this ticket here:

https://github.com/cr-ste-justine/clin-project/issues/195

**Comment by vferretti** [comment]
The bug is the fact that when you click Back from Matheo's page, you get an empty list of patients.

**Comment by nyanofthemoon** [comment]
@vferretti To confirm.

Steps to reproduce:
- go to the patient search page
- in the input search field write "matheo" (do not submit by pressing enter)
- in the results returned below the input search field, click the result titled "Matheo Belanger"
- you will be redirected to the patient page for "Mathe Belanger"
- click the browser back button

Current Behavior:
![image.png](https://images.zenhubusercontent.com/5c05950b0a4f964ea1a04049/9472df80-32f3-4f89-8fad-d55366624e22)

Expected Behavior:
- the same results before we exited to the patient page for "Matheo Belanger" should still be present

**Comment by nyanofthemoon** [comment]
@vferretti Thank you for the screencast, the ticket is clear now.

**Comment by vferretti** [comment]
Je ne peux pas voir ce qu'il y a au dessus de la table dans la dernière image, mais je pense qu'on devrait retrouver la liste qu'on avait avant de quitter la page (ce qui va être utile quand on aura des facettes à gauche) mais il n'est pas nécessaire de garder l'état de la textbox avec le mot Mathéo dedans. La textbox devrait être vide quand on retourne sur cette page avec le Back.  
Donc, pour le moment, puisqu'on n'a pas de facette, ca veut dire qu'on va retrouver la liste complete des patients sans aucun critère de recherche appliqué. 
J'espère que c'est clair.

**Comment by denis-crsj** [comment]
Testé avec succès
