### ISSUE TITLE
Ajouter la fonction Highligh de ES dans la requête ES

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#244]
Selon les specifications du document Google, voici les Règles d'affichages:
Toujours afficher le Gene Symbol en première ligne 
Afficher ensuite un ou plusieurs des champs suivants sur une ligne différente pour chaque type pour lequel on a un match ou plusieurs matchs
Gene Aliases (Afficher que les alias pour lesquels on a un match (ICGC les affiche tous)
Gene Ensembl ID
Gene name
OMIM ID
HGNC ID 
NCBI Gene ID
La string qui matche doit être en caractère gras.

Pour ce faire, on doit demander à ES de nous fournir les raisons du match afin d'être en mesure de les afficher dans le UI

**Comment by latch2112** [comment]
donc, voici la nouvelle requête ES à considérer:
https://jsoneditoronline.org/#left=cloud.15de033e4e564dca95cb47564831f113&right=cloud.1743c19abf5b4053854b5e29bd95fc62

Dans le panel de gauche, on as la requête et celui de droite la réponse.

Pour simplifier la vie du dev front-end, on peut choisir le tag html qu'on veux que ES retourne dans la réponse...

Défaut c'est <em></em>

**Comment by luclemo** [comment]
@latch2112 Merci pour tout ça. Pour le tag par défaut, peut-on le changer pour le tag `<mark>`?

Exemple du output pour une recherche sur `bra` qui retourne BRAF:
`<mark>BRA</mark>F`

Merci!

**Comment by latch2112** [comment]
@nyanofthemoon Qu'est-ce que tu en penses ?

**Comment by latch2112** [comment]
The client is not written yet. The client is the purview of #234
La fonction Highlight de ElasticSearch permet d'illustrer pkoi le résultat de la requête a retourner tel ou tel résultat
ES retourne un objet de ce style-ci:
`"highlight" : {
          "name" : [
            "<em>BRISC</em> and <em>BRCA1</em> A complex member 2"
          ],
          "alias" : [
            "<em>BRE</em>",
            "<em>BRCC4</em>",
            "<em>BRCC45</em>"
          ]
        }`
Comme vous pouvez voir, ces strings peuvent être préformatter pour le front-end ou pas.
Ce ticket ne vas dicter ce que le front-end va afficher...  Ce ticket retourne ce qui doit être afficher.

**Comment by luclemo** [comment]
@nyanofthemoon Hmmm, it's not just "characteres gras" as there is also a background highlight color to be consistent with the facet search bar. That is why I was proposing the `mark` element as it's a bit more semantic, but ultimately the choice of code is not so important to me as much as the visual consistency with the rest of the app.

- The HiFi design file for the recherche par gene is complete and linked in #223
- There is a ticket #234 which is to implement the UI...

I think the implementation ticket was blocked or are we ready to start the FE?

If we _are_ ready to start building the components and you need me to create tickets for each little piece, can you please give me the bullet list of said pieces and I will create the tickets.

As an aside, I think there has been a misunderstanding of my role. I am not, nor have I ever been PO, PM, or anything of the sort. I have been creating tickets and doing some of that work as much as I can to help out in order to move the project forward. I will continue to do so in order to help, but I wanted to be clear on this.

**Comment by nyanofthemoon** [comment]
@latch2112 Yes. To clarify what I am saying; I mean that when you are looking for `BR`, you shoudl get a return like this:
`"highlight" : { "name" : [ "{{BRISC}} and {{BRCA1}} A complex member 2" ], "alias" : [ "{{BRE}}", "{{BRCC4}}", "{{BRCC45}}" ] }`

**Comment by luclemo** [comment]
The last comment is to explain why I need to you give me the bullet points— I am not going to break things down the way a developer would and I don't want to waste time creating tickets which you will have to re-write to discard.
