### ISSUE TITLE
Plan de développement du CI/CD

### ISSUE THREAD

**Issue by latch2112** [Ferlab-Ste-Justine/clin-project#264]
Écrire un plan de développement pour le CI/CD

**Comment by latch2112** [comment]
https://docs.google.com/document/d/14xr6CVn4vK_J-OtecAgJLXUk3qgPVINWh2wvEmGr4oE/edit#heading=h.25ekfvg93hqa

**Comment by latch2112** [comment]
Assign @Magnitus- and @nyanofthemoon  for peer review of the plan.

**Comment by Magnitus-** [comment]
I would add a task to automate the configuration of keycloak as I found it to be a pain point for automating the setup of an environment.

This looks promising, but the repo is not popular enough to simply be used without auditing the code and carefully testing things to make sure it works as advertised: https://github.com/mrparkers/terraform-provider-keycloak

> Avoir un petit environnement de tests de 1 ou 2 VMs, créer un cluster swarm

> Rechercher où hoster un environment :

I would be careful about not undershooting here. Insufficient resources have been a big source of pipeline instability at my previous company. 

We can star with fixed vms, but I would have a game plan to automatically add other vms (via terraform and ansible to the cluster), especially if Vincent grows the team.

As such, an environment that plays well with Terraform (any well known Cloud provider or a private Openstack with leftover hardware capacity will do) would be ideal.

Something that I thought about which might save on costs a little: Some of our infra is "immutable" (keycloak... Elasticsearch now, though it might not be in the future). We can re-run all the other integration tests when that infra changes, but otherwise we can deploy it once and re-use it across tests (as long as the load from all the tests is not too big... premature optimization maybe).

> Créer un script et une série d’action pour déployer:
> - a private docker Registry

I would tackle that one with care. I think a private registry might be desirable for production. For tests, we might end up having to create images per branch which will generate a lot of transient images (if you create image tags per branch which is my advice, we did it at my previous company and it was very nice). Even if we don't do it per branch, we'll accumulate past versions.

Managing those images with the company that used a private on-prem Gitlab Docker registry was a pain in the neck, but it wasn't at the company I was in that used an external Quay.io registry to manage images (we had a tag to delete non-prod images after like a month, but overall we never had to worry about disk space for our registry).

Unless regulations force us to use a private registry (which it won't for public tests on dummy data), I would leverage a public registry (Docker Hub or Quay.IO) for the tests. It will lighten the maintenance burden. Managing registry disk space is not something either of us want to spend too much time with.

> Créer un script et une série d’action pour déployer:
> ES
> Keycloak
> Redis
> AidBox

See: https://github.com/cr-ste-justine/overture-dev-clin/blob/master/launch_dependencies.sh

We need to add Keycloak config automation (see my comment earlier), decouple the steps per pipeline instead of in a centralized script and add your bio-info stuff.

> Plugger une action de mise-à-jour du google spreadsheet et d’un push et ou un Tag pour amorcer l’import complet dans Aidbox

Please, not this. Maybe instead we can have a script to generate a bunch of json/yaml/xml/YourPick from the Spreadsheets and commit the generated documents to some Git repo that would trigger the pipeline.

**Comment by latch2112** [comment]
Thanks for your comments.  Really appreciated. I'll reuse them where appropriate on their respective stories.

**Comment by nyanofthemoon** [comment]
> I would be careful about not undershooting here. Insufficient resources have been a big source of pipeline instability at my previous company.

Agreed. Hopefully we get some decent budget for that.

> Please, not this. Maybe instead we can have a script to generate a bunch of json/yaml/xml/YourPick from the Spreadsheets and commit (and merge with a code-reviewed PR) the generated documents to some Git repo that would trigger the pipeline.

That dataset is meant as a temporary solution; I agree with this better solution principle but, I am not quite 100% convinced on the shelf life value... but I am convinced that it is not worth the stress when it goes wrong; perhaps a backup or dump would be a good in-between?

> Something that I thought about which might save on costs a little: Some of our infra is "immutable" (keycloak... Elasticsearch now, though it might not be in the future). We can re-run all the other integration tests when that infra changes, but otherwise we can deploy it once and re-use it across tests (as long as the load from all the tests is not too big... premature optimization maybe).

I'd opt for tackling that problem once (if) we get to it for the sake of simplicity. This would bring wider issues than just this one should it ever gets decided on a flexible architecture with "customizable providers". Let's focus on keeping everything clean and separate; that'd be the basic requirement to resolve this problem. ;)

**Comment by nyanofthemoon** [comment]
I'm worried about limiting the run-time of the pipeline by not testing "non-forward" dependencies. Example: a change to FHIR data or clin-proxy-api triggers re-building Cellbase.

**Comment by latch2112** [comment]
![CICD.png](https://images.zenhubusercontent.com/5c59d5e107cc4d6f39e559e4/2b0bf0e8-a754-4667-8646-85a2fac97e11)

FLOW of the full picture

**Comment by latch2112** [comment]
So, I agree that we need to decouple Google Spreadsheet but until we have the replacement piece, we need to find a way to manage our mock data. And since, it's only for the CI/CD and not for QA we could have a subset of the full mock...  and keep it on Github...  But we need a task to generate that subset when it need to changed...
